# Generated by Django 3.2.13 on 2022-07-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("votes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="choice",
            name="scores",
            field=models.IntegerField(default=0),
        ),
    ]
