# Generated by Django 3.2.13 on 2022-04-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_alter_artist_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='year_completed',
            field=models.IntegerField(default=0),
        ),
    ]
