# Generated by Django 3.2.13 on 2022-04-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0010_auto_20220424_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='artwork_medium',
            field=models.CharField(default='Fiber', max_length=200),
        ),
    ]
