# Generated by Django 3.2.13 on 2022-05-05 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0016_auto_20220505_1433"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="pub_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="pub_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
