# Generated by Django 3.2.13 on 2022-05-05 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0017_auto_20220505_1603"),
    ]

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("pronouns", models.CharField(max_length=200)),
                ("bio", models.TextField()),
                ("pub_date", models.DateTimeField(verbose_name="date published")),
                ("artworks", models.ManyToManyField(blank=True, to="entries.Artwork")),
            ],
        ),
    ]
