# Generated by Django 3.2.13 on 2022-05-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0019_artwork_medium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='artwork_medium',
        ),
        migrations.AlterField(
            model_name='artwork',
            name='year_completed',
            field=models.IntegerField(default=2022),
        ),
    ]
