# Generated by Django 3.2.13 on 2022-07-05 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0021_alter_artwork_medium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='vote_average',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='vote_total',
        ),
    ]
