# Generated by Django 3.2.13 on 2022-07-09 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0023_artwork_height_in_feet"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artwork",
            name="medium",
        ),
    ]
