# Generated by Django 3.2.13 on 2022-07-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0024_remove_artwork_medium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='height_in_feet',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
