# Generated by Django 3.2.13 on 2022-11-14 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0025_alter_artwork_height_in_feet"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Artist",
        ),
    ]
