# Generated by Django 3.2.13 on 2022-11-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0026_delete_artist"),
    ]

    operations = [
        migrations.AddField(
            model_name="artwork",
            name="medium",
            field=models.CharField(
                choices=[
                    ("Painting", "PAINTING"),
                    ("Sculpture", "SCULPTURE"),
                    ("Photography", "PHOTO"),
                    ("Ceramic", "CERAMIC"),
                    ("Textile", "TEXTILE"),
                    ("Print", "PRINT"),
                    ("Digital", "DIGITAL"),
                    ("Other", "OTHER"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("pronouns", models.CharField(max_length=200)),
                ("bio", models.TextField()),
                ("pub_date", models.DateTimeField(verbose_name="date published")),
                ("artworks", models.ManyToManyField(blank=True, to="entries.Artwork")),
            ],
        ),
    ]
