# Generated by Django 3.2.13 on 2022-12-09 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0028_auto_20221207_1340"),
    ]

    operations = [
        migrations.AddField(
            model_name="artwork",
            name="demo_link",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="artwork",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="artwork",
            name="source_link",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="artwork",
            name="vote_ratio",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="artwork",
            name="vote_total",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
