# Generated by Django 3.2.13 on 2022-12-31 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0029_auto_20221209_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
