# Generated by Django 3.2.13 on 2023-01-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0031_auto_20230101_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='value',
            field=models.CharField(choices=[('one', 1), ('two', 2), ('three', 3), ('four', 4), ('five', 5)], max_length=200),
        ),
    ]
