# Generated by Django 3.2.13 on 2023-01-11 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0032_alter_review_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='height_in_feet',
        ),
    ]
